update talks html links
hacsoc/hacsoc.github.com pull request #24
Opened 2016-10-15 19:26 UTC by ramon349

with this update i changed  link to the talk proposal form. It was originally set for spring 2016.  if someone can check if my small change on line 7 doesn't break the website that would be great.

2016-10-15 19:33 UTC, thomasrussellmurphy commented
Changing the link shouldn't break anything. I would recommend keeping the explicit `http://` in the link. Using `https://` also wouldn't be a problem.

2016-10-16 00:53 UTC, ajm188 commented
@thomasrussellmurphy I believe the protocol is required. Isn't it a relative link otherwise?

@ramon349 you should confirm the changes locally; `jekyll serve`, then visit the page you changed and verify you didn't break anything.

2016-10-16 00:54 UTC, ajm188 requested changes
please include the https protocol in the href

2016-10-16 01:01 UTC, thomasrussellmurphy commented
:unicodeshruge: It indeed may be, thus the link wouldn't be happy. Local testing is a good plan.

2019-11-01 05:39 UTC, closed without merging